version: "2"

services:
  # 安装redis
  redis:
    restart: always
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data/src:/src

  # 安装mysql
  mysql:
    restart: always
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/data/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fow
      MYSQL_USER: user
      MYSQL_PASSWORD: root

  # 安装mongodb
  mongo:
      restart: always
      image: mongo
      ports:
        - "27017:27017"
      volumes:
        - /mongo/data/db:/data/db
