version: '3'
services:
  web:
    image: nginx
    restart: always
    volumes:
       - /home/chr/docker/nginx/web/:/usr/share/nginx/html/:ro
       - /home/chr/docker/nginx/config/:/etc/nginx/conf.d/:ro
       - /home/chr/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "6001:6001"
      - "6002:6002"
      - "6003:6003"
    environment:
      - NGINX_HOST=demo.com
      - NGINX_PORT=80
